[profile.default]
src = "src"
out = "out"
libs = ["lib"]
solc_version = '0.8.26'
evm_version = 'cancun'
via_ir = true

[fuzz]
runs = 5000

[rpc_endpoints]
mainnet = "${MAINNET_RPC_URL}"
sepolia = "${SEPOLIA_RPC_URL}"
polygon = "${POLYGON_RPC_URL}"
polygon_mumbai = "${POLYGON_MUMBAI_RPC_URL}"
base = "${BASE_RPC_URL}"
base_sepolia = "${BASE_SEPOLIA_RPC_URL}"
arbitrum = "${ARBITRUM_RPC_URL}"
arbitrum_sepolia = "${ARBITRUM_SEPOLIA_RPC_URL}"
optimism = "${OPTIMISM_RPC_URL}"
basebsc = "${BSC_RPC_URL}"
bsc_testnet = "${BSC_TESTNET_RPC_URL}"
avalanche = "${AVALANCHE_RPC_URL}"
avalanche_fuji = "${AVALANCHE_FUJI_RPC_URL}"
celo = "${CELO_RPC_URL}"
celo_alfajores = "${CELO_ALFAJORES_RPC_URL}"
blast = "${BLAST_RPC_URL}"
blast_sepolia = "${BLAST_SEPOLIA_RPC_URL}"
zora = "${ZORA_RPC_URL}"
zora_sepolia = "${ZORA_SEPOLIA_RPC_URL}"

# See more config options https://github.com/foundry-rs/foundry/blob/master/crates/config/README.md#all-options
